### ISSUE TITLE
panic during generate

### ISSUE THREAD

**Issue by ScottWallace** [Brendonovich/prisma-client-rust#140]
Long-time Prisma user, really looking forward to this Rust release.

Got this doing a generate:

```
{"jsonrpc":"2.0","id":1,"result":{"manifest":{"defaultOutput":"prisma.rs","denylist":null,"prettyName":"Prisma Client Rust","requiresEngines":null,"requiresGenerators":null}}}
thread 'main' panicked at 'dmmf.datamodel.models[4].uniqueIndexes[0]: missing field `internalName` at line 1 column 58481', /Users/scottwallace/.cargo/registry/src/github.com-1ecc6299db9ec823/prisma-client-rust-0.2.1/src/main.rs:74:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

with RUST_BACKTRACE=1:

```
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
   3: prisma_client_rust::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

with RUST_BACKTRACE=FULL:

```
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  27:        0x1022084e8 - std::rt::lang_start_internal::h92a00ef694077615
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:20
  28:        0x1020345fc - _main
```

Nothing here for me to give a further hint on what's happening, except the mention of `uniqueIndexes[0]: missing field internalName`. Not sure what it's hinting at.

My employer won't allow sharing of the `schema.prisma` file. Anything in particular I should be looking for?

**Comment by Brendonovich** [comment]
Not quite sure what's happening. If you're unable to share your schema, can you try creating a minimum reproducible example that is different enough to the actual schema that you can share it? Not a lot I can do without a schema, sorry
