### ISSUE TITLE
Prisma generate not working

### ISSUE THREAD

**Issue by timurguvenkaya** [Brendonovich/prisma-client-rust#301]
I'm trying to integrate rust prisma client into my next.js app with Rust vercel runtime, but when I do cargo prisma generate I get:

Generator at MY_PATH/webapp/node_modules/@prisma/client/generator-build/index.js could not start:

node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module 'MY_PATH/webapp/backend/--max-old-space-size=8096'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

I tried both installing cli using /bin and workspaces method. None of them worked.  I already have JS prisma client integrated, can it be an issue?

**Comment by timurguvenkaya** [comment]
Found my mistake :) 
Apologies

**Comment by merlindru** [comment]
Running into this as well. How did you fix it?
