### ISSUE TITLE
In the transaction, use the batch operation to update the data problem

### ISSUE THREAD

**Issue by tingfeng-key** [Brendonovich/prisma-client-rust#336]
In a transaction, using the `batch`+`create`/`update`/`delete` combination will cause an exception.
First of all, my problem was caused by `update` first, and then I tested the same problem with create, and guessed that `delete` is also the same.
code show as below:
![image](https://github.com/Brendonovich/prisma-client-rust/assets/13976521/41ebb8f7-4b59-47a4-b310-d7dec806e05a)

errors:
```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QueryError("Error executing query: Unknown - Error occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.\n\nStack backtrace:\n   0: std::backtrace_rs::backtrace::dbghelp::trace\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917/library\\std\\src\\..\\..\\backtrace\\src\\backtrace\\dbghelp.rs:98\n   1: std::backtrace_rs::backtrace::trace_unsynchronized\n
 at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917/library\\std\\src\\..\\..\\backtrace\\src\\backtrace\\mod.rs:66\n   2: std::backtrace::Backtrace::create\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917/library\\std\\src\\backtrace.rs:332\n   3: std::backtrace::Backtrace::capture\n
  at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917/library\\std\\src\\backtrace.rs:298\n   4: anyhow::error::impl$2::from<enum2$<quaint::error::ErrorKind> >\n             at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\anyhow-1.0.71\\src\\error.rs:547\n   5: core::convert::impl$3::into<enum2$<quaint::error::ErrorKind>,anyhow::Error>\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\core\\src\\convert\\mod.rs:717\n   6: enum2$<sql_query_connector::error::SqlError>::into_connector_error\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\connectors\\sql-query-connector\\src\\error.rs:197\n   7: sql_query_connector::database::catch::async_fn$0<prisma_models::selection_result::SelectionResult,enum2$<sql_query_connector::database::transaction::impl$4::create_record::async_block$0::async_block_env$0> >\n     
        at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\connectors\\sql-query-connector\\src\\database\\mod.rs:53\n   8: sql_query_connector::database::transaction::impl$4::create_record::async_block$0\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\connectors\\sql-query-connector\\src\\database\\transaction.rs:154\n   9: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<prisma_models::selection_result::SelectionResult,query_connector::error::ConnectorError> > > >,core::marker::Send>,alloc::allo\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\core\\src\\future\\future.rs:125\n  10: query_core::interpreter::query_interpreters::write::create_one::async_fn$0\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\interpreter\\query_interpreters\\write.rs:46\n  11: query_core::interpreter::query_interpreters::write::execute::async_fn$0\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\interpreter\\query_interpreters\\write.rs:14\n  12: tracing::instrument::impl$0::poll<enum2$<query_core::interpreter::query_interpreters::write::execute::async_fn_env$0> >\n             at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tracing-0.1.37\\src\\instrument.rs:272\n  13: query_core::interpreter::interpreter_impl::impl$4::interpret::async_block$4\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\interpreter\\interpreter_impl.rs:243\n  14: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<enum2$<query_core::interpreter::interpreter_impl::ExpressionResult>,enum2$<query_core::interpreter::error::InterpreterError> >\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\core\\src\\future\\future.rs:125\n  15: query_core::interpreter::interpreter_impl::impl$4::interpret::async_block$0\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\interpreter\\interpreter_impl.rs:179\n  16: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<enum2$<query_core::interpreter::interpreter_impl::ExpressionResult>,enum2$<query_core::interpreter::error::InterpreterError> >\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\core\\src\\future\\future.rs:125\n  17: query_core::interpreter::interpreter_impl::impl$4::interpret::async_block$3\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\interpreter\\interpreter_impl.rs:212\n  18: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<enum2$<query_core::interpreter::interpreter_impl::ExpressionResult>,enum2$<query_core::interpreter::error::InterpreterError> >\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\core\\src\\future\\future.rs:125\n  19: query_core::interpreter::interpreter_impl::impl$4::interpret::async_block$3\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\interpreter\\interpreter_impl.rs:212\n  20: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<enum2$<query_core::interpreter::interpreter_impl::ExpressionResult>,enum2$<query_core::interpreter::error::InterpreterError> >\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\core\\src\\future\\future.rs:125\n  21: query_core::interpreter::interpreter_impl::impl$4::interpret::async_block$3\n    
         at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\interpreter\\interpreter_impl.rs:223\n  22: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<enum2$<query_core::interpreter::interpreter_impl::ExpressionResult>,enum2$<query_core::interpreter::error::InterpreterError> >\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\core\\src\\future\\future.rs:125\n  23: query_core::interpreter::interpreter_impl::impl$4::interpret::async_block$3\n
   at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\interpreter\\interpreter_impl.rs:212\n  
24: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<enum2$<query_core::interpreter::interpreter_impl::ExpressionResult>,enum2$<query_core::interpreter::error::InterpreterError> >\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\core\\src\\future\\future.rs:125\n  25: query_core::interpreter::interpreter_impl::impl$4::interpret::async_block$3\n             at 
C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\interpreter\\interpreter_impl.rs:223\n  26: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<enum2$<query_core::interpreter::interpreter_impl::ExpressionResult>,enum2$<query_core::interpreter::error::InterpreterError> >\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\core\\src\\future\\future.rs:125\n  27: query_core::interpreter::interpreter_impl::impl$4::interpret::async_block$2\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\interpreter\\interpreter_impl.rs:191\n  28: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<enum2$<query_core::interpreter::interpreter_impl::ExpressionResult>,enum2$<query_core::interpreter::error::InterpreterError> >\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\core\\src\\future\\future.rs:125\n  29: tracing::instrument::impl$0::poll<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<enum2$<query_core::interpreter::interpreter_impl::ExpressionResult>,enum2$<query_core::interpreter::error::Inter\n    
         at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tracing-0.1.37\\src\\instrument.rs:272\n  30: query_core::executor::pipeline::impl$0::execute::async_fn$0\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\executor\\pipeline.rs:35\n  31: query_core::executor::execute_operation::execute_on::async_fn$0\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\executor\\execute_operation.rs:267\n  32: query_core::executor::execute_operation::execute_many_operations::async_fn$0\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\executor\\execute_operation.rs:47\n  33: tokio::task::task_local::impl$3::poll::closure$0<query_core::executor::request_context::RequestContext,enum2$<query_core::executor::execute_operation::execute_many_operations::async_fn_env$0> >\n             at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tokio-1.28.1\\src\\task\\task_local.rs:348\n  34: tokio::task::task_local::LocalKey<query_core::executor::request_context::RequestContext>::scope_inner<query_core::executor::request_context::RequestContext,tokio::task::task_local::impl$3::poll::closure_env$0<query_core::executor::request_context::Request\n             at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tokio-1.28.1\\src\\task\\task_local.rs:233\n  35: tokio::task::task_local::impl$3::poll<query_core::executor::request_context::RequestContext,enum2$<query_core::executor::execute_operation::execute_many_operations::async_fn_env$0> >\n             at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tokio-1.28.1\\src\\task\\task_local.rs:345\n  36: query_core::executor::request_context::with_request_context::async_fn$0<enum2$<query_core::executor::execute_operation::execute_many_operations::async_fn_env$0>,enum2$<core::result::Result<alloc::vec::Vec<enum2$<core::result::Result<query_core::response_i\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\executor\\request_context.rs:64\n  37: query_core::executor::interpreting_executor::impl$1::execute_all::async_block$0<sql_query_connector::database::sqlite::Sqlite>\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-engines-8e1416dd0e571d11\\45b026c\\query-engine\\core\\src\\executor\\interpreting_executor.rs:113\n  38: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<alloc::vec::Vec<enum2$<core::result::Result<query_core::response_ir::response::ResponseData,enum2$<query_core::error::CoreErro\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\core\\src\\future\\future.rs:125\n  39: prisma_client_rust::client::impl$0::execute_all::async_fn$0\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-client-rust-fa967aa5ad0ec391\\113b48d\\crates\\lib\\src\\client.rs:83\n  40: prisma_client_rust::queries::batch::batch::async_fn$0<alloc::vec::Vec<prisma_client_rust::queries::create::Create<service::prisma::system_role_menu::Types>,alloc::alloc::Global>,tuple$<> >\n             at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-client-rust-fa967aa5ad0ec391\\113b48d\\crates\\lib\\src\\queries\\batch.rs:94\n  41: service::prisma::_prisma::impl$2::_batch::async_fn$0<alloc::vec::Vec<prisma_client_rust::queries::create::Create<service::prisma::system_role_menu::Types>,alloc::alloc::Global>,tuple$<> >\n             at .\\service\\src\\prisma.rs:11123\n  42: cli::menu::init::async_fn$0::closure$0::async_block$0\n             at .\\app\\cli\\src\\menu.rs:12\n  43: prisma_client_rust::transaction::impl$0::run::async_fn$0<service::prisma::_prisma::PrismaClient,enum2$<service::ServiceError>,tuple$<>,enum2$<cli::menu::init::async_fn$0::closure$0::async_block_env$0>,cli::menu::init::async_fn$0::closure_env$0>\n     
        at C:\\Users\\ld_100\\.cargo\\git\\checkouts\\prisma-client-rust-fa967aa5ad0ec391\\113b48d\\crates\\lib\\src\\transaction.rs:59\n  44: cli::menu::init::async_fn$0\n             at .\\app\\cli\\src\\menu.rs:15\n  45: cli::main::async_block$0\n             at .\\app\\cli\\src\\main.rs:26\n  46: tokio::runtime::park::impl$4::block_on::closure$0<enum2$<cli::main::async_block_env$0> >\n             at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tokio-1.28.1\\src\\runtime\\park.rs:283\n  47: tokio::runtime::coop::with_budget\n             at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tokio-1.28.1\\src\\runtime\\coop.rs:107\n  48: tokio::runtime::coop::budget\n             at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tokio-1.28.1\\src\\runtime\\coop.rs:73\n  49: tokio::runtime::park::CachedParkThread::block_on<enum2$<cli::main::async_block_env$0> >\n             at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tokio-1.28.1\\src\\runtime\\park.rs:283\n  50: tokio::runtime::context::BlockingRegionGuard::block_on<enum2$<cli::main::async_block_env$0> >\n             at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tokio-1.28.1\\src\\runtime\\context.rs:315\n  51: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<enum2$<cli::main::async_block_env$0> >\n             at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tokio-1.28.1\\src\\runtime\\scheduler\\multi_thread\\mod.rs:66\n  52: tokio::runtime::runtime::Runtime::block_on<enum2$<cli::main::async_block_env$0> >\n             at C:\\Users\\ld_100\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tokio-1.28.1\\src\\runtime\\runtime.rs:304\n  53: cli::main\n             at .\\app\\cli\\src\\main.rs:24\n  54: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> 
>\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\core\\src\\ops\\function.rs:250\n  55: std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\std\\src\\sys_common\\backtrace.rs:134\n  
56: std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\std\\src\\sys_common\\backtrace.rs:134\n  57: std::rt::lang_start::closure$0<tuple$<> >\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\std\\src\\rt.rs:166\n  58: std::rt::lang_start_internal::closure$2\n 
            at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917/library\\std\\src\\rt.rs:148\n  59: std::panicking::try::do_call\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917/library\\std\\src\\panicking.rs:485\n  60: std::panicking::try\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917/library\\std\\src\\panicking.rs:449\n  61: std::panic::catch_unwind\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917/library\\std\\src\\panic.rs:140\n  62: std::rt::lang_start_internal\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917/library\\std\\src\\rt.rs:148\n  63: std::rt::lang_start<tuple$<> >\n             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\\library\\std\\src\\rt.rs:165\n  64: main\n  65: invoke_main\n             at d:\\a01\\_work\\20\\s\\src\\vctools\\crt\\vcstartup\\src\\startup\\exe_common.inl:78\n  66: __scrt_common_main_seh\n             at d:\\a01\\_work\\20\\s\\src\\vctools\\crt\\vcstartup\\src\\startup\\exe_common.inl:288\n  67: BaseThreadInitThunk\n  68: RtlUserThreadStart), transient: false })")', app\cli\src\main.rs:26:32
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917/library\std\src\panicking.rs:578
   1: core::panicking::panic_fmt
             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917/library\core\src\result.rs:1651
   3: enum2$<core::result::Result<tuple$<>,enum2$<service::ServiceError> > >::unwrap<tuple$<>,enum2$<service::ServiceError> >
             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\library\core\src\result.rs:1076
   4: cli::main::async_block$0
             at .\app\cli\src\main.rs:26
   5: tokio::runtime::park::impl$4::block_on::closure$0<enum2$<cli::main::async_block_env$0> >
             at C:\Users\ld_100\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\park.rs:283
   6: tokio::runtime::coop::with_budget
             at C:\Users\ld_100\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\coop.rs:107
   7: tokio::runtime::coop::budget
             at C:\Users\ld_100\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\coop.rs:73
   8: tokio::runtime::park::CachedParkThread::block_on<enum2$<cli::main::async_block_env$0> >
             at C:\Users\ld_100\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\park.rs:283
   9: tokio::runtime::context::BlockingRegionGuard::block_on<enum2$<cli::main::async_block_env$0> >
             at C:\Users\ld_100\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\context.rs:315
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on<enum2$<cli::main::async_block_env$0> >  
             at C:\Users\ld_100\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\scheduler\multi_thread\mod.rs:66
  11: tokio::runtime::runtime::Runtime::block_on<enum2$<cli::main::async_block_env$0> >
             at C:\Users\ld_100\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.28.1\src\runtime\runtime.rs:304
  12: cli::main
             at .\app\cli\src\main.rs:24
  13: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/c4190f2d3a46a59f435f7b42f58bc22b2f4d6917\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\cli.exe menu-init` (exit code: 101)
```

**Comment by Brendonovich** [comment]
Hmm I think this is because you're using `_batch` inside `_transaction`. Technically it's not actually allowed, but I didn't bother to enforce it at a type-level. If that is the problem then I may have to try using some generics to make sure `_batch` isn't called inside `_transaction`

**Comment by tingfeng-key** [comment]
Ok, While I was trying to solve it the other way (change all operations to batch), so I ran into another problem, I tried to put the update and create into a Vec, I tried the Traits I knew, and I wanted to implement it through the dyn trait, and I found that it didn't work. Finally, I found that `QueryConvert` and `Query` trait do not meet the requirements of the trait object. My code is probably like this. It is conditionally pushed to Vec：
```rust
let mut batch_querys = vec![];
if let Some(keyword) = params.keyword {
    batch_querys.push(
        client
            .system_role()
            .update_unchecked(system_role::id::equals(id), params.to_params()),
    )
}
if let Some(username) = params.username {
    batch_querys.push(system_role::create(&new_client, role.id, x.id));
}
client._batch(batch_querys).await?;
```
Of course, there are other solutions to my current problems (not necessarily the case), but this can be more convenient

**Comment by tingfeng-key** [comment]
```rust
let mut batch_querys: Vec<Box<dyn SetQuery<
   RawType = system_role_menu::Data, ReturnValue = system_role_menu::Data,>,>,> = Vec::new();
```
Here is the variable I am trying to define, try using trait object

**Comment by Brendonovich** [comment]
`_batch` doesn't work with `dyn SetQuery`, it works with concrete types. For your example, you want to batch a `system_role().update_unchecked()` and a `system_role().create()`, which are distinct types and so can't be put into a `Vec`. Instead, you'll need to use a tuple with an entry for each query - but the fact that each query is optional means that you'll then need to wrap the queries in a `Vec`, since if each query isn't actually needed then an empty `Vec` should be provided instead:

```rust
client._batch((
  params.keyword.map(|keyword| {
    client.system_role().update_unchecked(...),
  }).into_iter().collect::<Vec<_>>(),
  params.username.map(|username| {
    client.system_role().create(...)
  }).into_iter().collect::<Vec<_>>()
)).await?;
```
