### ISSUE TITLE
[bug] ERR_NO_ICU

### ISSUE THREAD

**Issue by Massimiliano-solutiontech** [Brendonovich/prisma-client-rust#352]
On Windows 11 ARM I'm getting `TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU` after launch `cargo prisma generate`

```sh
❯ cargo prisma generate
    Finished dev [unoptimized + debuginfo] target(s) in 0.46s
warning: the following packages contain code that will be rejected by a future version of Rust: bigint v4.4.3, connection-string v0.1.13
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `target\debug\prisma-cli.exe generate`
node:internal/encoding:469
          throw new ERR_NO_ICU('"fatal" option');
          ^

TypeError [ERR_NO_ICU]: "fatal" option is not supported on Node.js compiled without ICU
    at new NodeError (node:internal/errors:372:5)
    at new TextDecoder (node:internal/encoding:469:17)
    at ../../node_modules/.pnpm/@prisma+prisma-fmt-wasm@4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe/node_modules/@prisma/prisma-fmt-wasm/src/prisma_fmt_build.js (C:\snapshot\node_modules\prisma\build\index.js:11956:29)  
    at __require (C:\snapshot\node_modules\prisma\build\index.js:14:50)
    at Object.<anonymous> (C:\snapshot\node_modules\prisma\build\index.js:86332:38)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12) {
  code: 'ERR_NO_ICU'
}
```

**Comment by Brendonovich** [comment]
No idea what this means sorry, I'm not sure Prisma is tested on Windows ARM at all 😅

**Comment by Massimiliano-solutiontech** [comment]
Ahah no problem, should I open this issue on the Prisma respo?

**Comment by Brendonovich** [comment]
I guess so, idk if they'll be too interested tho since it's probably not reproduceable in the JS client
