### ISSUE TITLE
Issue using nodejs generator

### ISSUE THREAD

**Issue by JulianRuiseco** [Brendonovich/prisma-client-rust#354]
We are trying to make a small service to run some JS code alongside our rust server. 

We placed the following

`
generator nodejs {
  provider = "prisma-client-js"
  output   = "../op3_parser/node_modules/.prisma/client"
}
`

and received the following error

`
Error: Generator at path\bob_server\node_modules\@prisma\client\generator-build\index.js could not start:

node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module 'path\bob_server\--max-old-space-size=8096'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

`

I can confirm that the process runs correctly when triggered from npm

**Comment by JulianRuiseco** [comment]
Thank you!
