### ISSUE TITLE
If there are multiple relationships of the same type on one model, specifying seperate names fails 

### ISSUE THREAD

**Issue by Suyashtnt** [Brendonovich/prisma-client-rust#73]
Schema
```prisma
datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

generator client {
  provider        = "cargo prisma"
  output          = "../src/prisma.rs"
  previewFeatures = ["referentialIntegrity"]
}

model User {
  id String @id

  gamesPlayedAsWhite Game[] @relation(name: "playerWhite")
  gamesPlayedAsBlack Game[] @relation(name: "playerBlack")

  OutcomesAsWhite Outcome[] @relation("whiteOutcome")
  OutcomesAsBlack Outcome[] @relation("blackOutcome")
}

model Game {
  id         String   @id @default(cuid())
  timePlayed DateTime @default(now())

  white   User   @relation(fields: [whiteId], references: [id], name: "playerWhite")
  whiteId String

  black   User   @relation(fields: [blackId], references: [id], name: "playerBlack")
  blackId String

  whiteOutcome   Outcome @relation(fields: [whiteOutcomeId], references: [id], name: "whiteOutcome")
  whiteOutcomeId String

  blackOutcome   Outcome @relation(fields: [blackOutcomeId], references: [id], name: "blackOutcome")
  blackOutcomeId String
}

model Outcome {
  id String @id @default(cuid())

  white   User   @relation(fields: [whiteId], references: [id], name: "whiteOutcome")
  whiteId String

  black   User   @relation(fields: [blackId], references: [id], name: "blackOutcome")
  blackId String

  whiteResult OutcomeResult
  blackResult OutcomeResult

  userId String?
  gameId String?

  GameAsWhite Game[] @relation("whiteOutcome")
  GameAsBlack Game[] @relation("blackOutcome")
}

/// This is for player1
enum OutcomeResult {
  WIN
  LOSS
  DRAW
}
```

Console output:
```
The database is already in sync with the Prisma schema.

Running generate... (Use --skip-generate to skip the generators)
Error: Schema parsing
thread 'main' panicked at 'It's not allowed that both sides of a relation specify the inline policy. The field was whiteOutcome on model Game. The related field was white on model Outcome.', query-engine/prisma-models/src/builders/internal_dm_builder.rs:371:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: <prisma_models::builders::internal_dm_builder::InternalDataModelBuilder as core::convert::From<&dml::datamodel::Datamodel>>::from
   3: query_engine::main::{{closure}}
   4: std::thread::local::LocalKey<T>::with
   5: tokio::park::thread::CachedParkThread::block_on
   6: tokio::runtime::thread_pool::ThreadPool::block_on
   7: tokio::runtime::Runtime::block_on
   8: query_engine::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Suyashtnt** [comment]
The code is bad, but it does show this error. I've cleaned up the code so it longer has this issue, but it's still an issue

**Comment by Brendonovich** [comment]
This isn't a problem with Prisma Client Rust, but with your schema. I'm not exactly sure what the problem is, but I believe it's because you're using `@relation` on both sides of the `Game <-> Outcome` relation. The [Prisma docs](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/one-to-one-relations) show that 1-1 relations should only have `@relation` on one side.
